# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AccessToken(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, message: str=None, access_token: str=None, refresh_token: str=None):  # noqa: E501
        """AccessToken - a model defined in Swagger

        :param message: The message of this AccessToken.  # noqa: E501
        :type message: str
        :param access_token: The access_token of this AccessToken.  # noqa: E501
        :type access_token: str
        :param refresh_token: The refresh_token of this AccessToken.  # noqa: E501
        :type refresh_token: str
        """
        self.swagger_types = {
            'message': str,
            'access_token': str,
            'refresh_token': str
        }

        self.attribute_map = {
            'message': 'message',
            'access_token': 'access_token',
            'refresh_token': 'refresh_token'
        }

        self._message = message
        self._access_token = access_token
        self._refresh_token = refresh_token

    @classmethod
    def from_dict(cls, dikt) -> 'AccessToken':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AccessToken of this AccessToken.  # noqa: E501
        :rtype: AccessToken
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this AccessToken.


        :return: The message of this AccessToken.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this AccessToken.


        :param message: The message of this AccessToken.
        :type message: str
        """

        self._message = message

    @property
    def access_token(self) -> str:
        """Gets the access_token of this AccessToken.


        :return: The access_token of this AccessToken.
        :rtype: str
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token: str):
        """Sets the access_token of this AccessToken.


        :param access_token: The access_token of this AccessToken.
        :type access_token: str
        """

        self._access_token = access_token

    @property
    def refresh_token(self) -> str:
        """Gets the refresh_token of this AccessToken.


        :return: The refresh_token of this AccessToken.
        :rtype: str
        """
        return self._refresh_token

    @refresh_token.setter
    def refresh_token(self, refresh_token: str):
        """Sets the refresh_token of this AccessToken.


        :param refresh_token: The refresh_token of this AccessToken.
        :type refresh_token: str
        """

        self._refresh_token = refresh_token
