# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UserWithOutPassword(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, username: str=None, first_name: str=None, last_name: str=None, email: str=None):  # noqa: E501
        """UserWithOutPassword - a model defined in Swagger

        :param id: The id of this UserWithOutPassword.  # noqa: E501
        :type id: str
        :param username: The username of this UserWithOutPassword.  # noqa: E501
        :type username: str
        :param first_name: The first_name of this UserWithOutPassword.  # noqa: E501
        :type first_name: str
        :param last_name: The last_name of this UserWithOutPassword.  # noqa: E501
        :type last_name: str
        :param email: The email of this UserWithOutPassword.  # noqa: E501
        :type email: str
        """
        self.swagger_types = {
            'id': str,
            'username': str,
            'first_name': str,
            'last_name': str,
            'email': str
        }

        self.attribute_map = {
            'id': 'id',
            'username': 'username',
            'first_name': 'firstName',
            'last_name': 'lastName',
            'email': 'email'
        }

        self._id = id
        self._username = username
        self._first_name = first_name
        self._last_name = last_name
        self._email = email

    @classmethod
    def from_dict(cls, dikt) -> 'UserWithOutPassword':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserWithOutPassword of this UserWithOutPassword.  # noqa: E501
        :rtype: UserWithOutPassword
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this UserWithOutPassword.


        :return: The id of this UserWithOutPassword.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this UserWithOutPassword.


        :param id: The id of this UserWithOutPassword.
        :type id: str
        """

        self._id = id

    @property
    def username(self) -> str:
        """Gets the username of this UserWithOutPassword.


        :return: The username of this UserWithOutPassword.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this UserWithOutPassword.


        :param username: The username of this UserWithOutPassword.
        :type username: str
        """

        self._username = username

    @property
    def first_name(self) -> str:
        """Gets the first_name of this UserWithOutPassword.


        :return: The first_name of this UserWithOutPassword.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name: str):
        """Sets the first_name of this UserWithOutPassword.


        :param first_name: The first_name of this UserWithOutPassword.
        :type first_name: str
        """

        self._first_name = first_name

    @property
    def last_name(self) -> str:
        """Gets the last_name of this UserWithOutPassword.


        :return: The last_name of this UserWithOutPassword.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name: str):
        """Sets the last_name of this UserWithOutPassword.


        :param last_name: The last_name of this UserWithOutPassword.
        :type last_name: str
        """

        self._last_name = last_name

    @property
    def email(self) -> str:
        """Gets the email of this UserWithOutPassword.


        :return: The email of this UserWithOutPassword.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this UserWithOutPassword.


        :param email: The email of this UserWithOutPassword.
        :type email: str
        """

        self._email = email
